version: '3.8'

services:
  # Development service
  dev:
    image: adityakxco:dev
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
    
  # # Production service
  # prod:
  #   image: adityakxco:prod
  #   build:
  #     context: .
  #     target: runner
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production